### ISSUE TITLE
Why so many url's in output?

### ISSUE THREAD

**Issue by Nikodemsky** [stechermichal/mangadex-rss#5]
I'm trying to get my head around the output it creates - basically i have feedUrlsList.txt with something like 16 url's, each contain chapters for various mangas i follow but i'm not sure how those are ordered by, how much actual latest chapters from my feed it grabs and why it's not structured like my actual feed, so it will get let's say 22 latest positions with it's chapters updated.

Url's in that feeds contains chapters from months ago, so it's not really latest content.

It feels... random. Am i missing something here?

**Comment by stechermichal** [comment]
feedUrlsList.txt should not contain chapters of the manga, it should contain premade links to [mdrss](https://mdrss.tijlvdb.me) where each contains 10 manga IDs in the URL, because 10 is the maximum per link. That URL then links to the updates of those 10 manga. 

So given that yours contains 16 long urls, I'm assuming you have around 150 manga that you follow and their new chapters show up in the Updates tab on Mangadex (https://mangadex.org/titles/feed).

So these 16 URLs now just need to make their way to the RSS reader of your choice. I don't know how yours particular one deals with sources, but I'm using built in Vivaldi browser RSS, where I've added 10 sources that then combine into the main "Feeds" folder where all updates are together and mirror what the MD Updates tab looks like.

My updates feed checks out with the rss notifications, because it was Friday 2 days ago: [https://i.imgur.com/xnzkK76.png](https://i.imgur.com/xnzkK76.png).

That was a bit of a roundabout explanation, so let me address your specific points directly:

> each contain chapters for various mangas i follow but i'm not sure how those are ordered by

I dunno how the manga is ordered in the URLs, but the chapters should be ordered by "latest 20 updates from newest to oldest". Once all the URLs are in your RSS reader, it should combine them and show them ordered by latest update.

> how much actual latest chapters from my feed it grabs and why it's not structured like my actual feed

Each feed has 20 latest updates. Why yours final result isn't the same I'm not sure, but if your feedUrlsList.txt has 16 urls, where each looks something like this:
https://mdrss.tijlvdb.me/feed?q=manga:cade38b7-64c4-4a29-8e3c-8c283291d6c6,tl:en&q=manga:d22ae7a1-cfae-475a-a8fc-589ef85eece4,tl:en&q=manga:c783711c-e593-44e9-83a1-8c95b7f703de,tl:en&q=manga:cddd1849-ab36-4304-8103-06ba4062b5e6,tl:en&q=manga:c5d731f9-c1cf-4a69-a797-cd9c2a58316b,tl:en&q=manga:bd6d0982-0091-4945-ad70-c028ed3c0917,tl:en&q=manga:cd2c9ef6-6b97-4e7e-868a-e853fa74ff63,tl:en&q=manga:d44c8d22-934c-4a4a-9346-0afd21264cca,tl:en&q=manga:bd2dd893-6bbc-4d6c-8c06-921318ef9ac0,tl:en&q=manga:dc481ed5-4925-4f3c-bac1-e73f1e7ed338,tl:en

then it seems that it's working fine and the issue is with your RSS reader.

You can also click on this link rather than add it to the RSS reader to see what updates that specific URL contains. This example url for example only has updates from 2 of the 10 manga in it, but that's just because the other 8 have had no updates. The last ID in the URL, `dc481ed5-4925-4f3c-bac1-e73f1e7ed338`, is this manga: https://mangadex.org/title/dc481ed5-4925-4f3c-bac1-e73f1e7ed338, which had the last update over a year ago - so it doesn't fit into the 20 limit of latest updates.

That shouldn't matter, the point of this tool is for RSS to notify you of new uploads, we don't really want the entire history of Mangadex Updates tab.

> why it's not structured like my actual feed, so it will get let's say 22 latest positions with it's chapters updated.

Yea, that's what we want and your RSS reader should mirror the Updates tab once it has taken all those 16 sources.

> Url's in that feeds contains chapters from months ago, so it's not really latest content.

Indeed that should not be the case, the url should contain the latest updates of those 10 manga in the URL. If that's not the case, can you link that specific URL here so I can have a look where the issue is?

**Comment by Nikodemsky** [comment]
Sure, here's the txt file:
https://mdfeed.w3wg.com/feedUrlsList.txt

Check the last url for the "older" chapters.

**Comment by stechermichal** [comment]
When I open the URLs from the file, what I get is indeed the last 20 updates of the 10 manga specified in the URL.
The last one for example gives me this:
[https://i.imgur.com/4OoDk4S.png](https://i.imgur.com/4OoDk4S.png)

Which checks out. That is the last update received for any of these 10 manga specified by their IDs that are listed in that URL. When put into an RSS reader that combines those links, the updates from all of those will be there in order.

What reader are you using? If it's still not working, I can have a look at how it works in your particular one.

**Comment by Nikodemsky** [comment]
RSS Guard.

I'm kind of looking for feed based on this if possible
![screencapture-mangadex-org-titles-feed-2024-11-24-22_22_03](https://github.com/user-attachments/assets/66d0f952-5f9f-4448-933d-4729f3c80c53)
but i'm guessing "Updates" feed might not be something i can achieve with mangadex-rss :\

**Comment by stechermichal** [comment]
Yea that's what we get, I think I was able to do it with the feedUrlsList.txt that you shared, thus getting a match between RSS Guard and the screenshot of your Updates feed you posted:
https://i.imgur.com/6dJ4QgM.png

I added 16 feeds one by one that belong under the main folder. You can create a new category called "manga" under which you would then add these. Then when that parent folder (in my case "michal(RSS/ATOM/JSON)") is selected, I'm getting all of the latest updates. The only difference is that MD "Updates" sometimes bunches up some chapters together, I think it does that in the cases where there were several updates with small delays? Like in the case of Fukuzatsu na Kyoudai no 4koma on your screenshot.

The RSS feed will just make a new line/notification each time there is an update.

Are you able to reach the same result?

PS: The way I added the feeds was that I selected the parent folder, right-click, Add new feed, Switch to advanced mode, paste the the first URL into the source field, click Fetch it now, OK. Repeat 16 times for each URL.

**Comment by Nikodemsky** [comment]
I'll check that out, thanks for taking your to explain! Really appreciate it.

**Comment by Nikodemsky** [comment]
Got it working, thanks once again!

**Comment by stechermichal** [comment]
I'm glad it worked out, no problem at all
